import fs from "node:fs";
import path from "node:path";
import type { OverlayFile, PrisonStateRecord, VerificationAuditRecord, VerificationStateFile } from "./types";
import { emptyOverlay, type OverlayStore } from "./applyChanges";

export function defaultVerificationDir(root = process.cwd()): string {
  return path.join(root, "data", "verification");
}

export function readJsonFile<T>(filePath: string, fallback: T): T {
  if (!fs.existsSync(filePath)) return fallback;
  const raw = fs.readFileSync(filePath, "utf8");
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export function writeJsonFile(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

export function fileOverlayStore(filePath: string): OverlayStore {
  return {
    read() {
      return readJsonFile<OverlayFile>(filePath, emptyOverlay());
    },
    write(file) {
      writeJsonFile(filePath, file);
    },
  };
}

export function memoryOverlayStore(initial: OverlayFile = emptyOverlay()): OverlayStore & { snapshot(): OverlayFile } {
  let current: OverlayFile = structuredClone(initial);
  return {
    read() {
      return structuredClone(current);
    },
    write(file) {
      current = structuredClone(file);
    },
    snapshot() {
      return structuredClone(current);
    },
  };
}

export function loadState(dir: string): VerificationStateFile {
  return readJsonFile<VerificationStateFile>(path.join(dir, "state.json"), { prisons: {} });
}

export function saveState(dir: string, state: VerificationStateFile): void {
  writeJsonFile(path.join(dir, "state.json"), state);
}

export function appendAudit(dir: string, record: VerificationAuditRecord): void {
  const filePath = path.join(dir, "audit.jsonl");
  fs.mkdirSync(dir, { recursive: true });
  fs.appendFileSync(filePath, `${JSON.stringify(record)}\n`, "utf8");
}

export function upsertPrisonState(
  state: VerificationStateFile,
  row: PrisonStateRecord,
): VerificationStateFile {
  return { prisons: { ...state.prisons, [row.prisonSlug]: row } };
}

export const OVERLAY_JSON_RELATIVE = "data/verification/overlay.json";
export const OVERLAY_TS_RELATIVE = "src/data/generated/ukVerificationOverlay.generated.ts";

export function renderOverlayModule(file: OverlayFile): string {
  return `/* eslint-disable */
/** Auto-generated by the UK prison verifier when writes are explicitly enabled. Dry-run never touches this file. */
import type { OverlayFile } from "@/lib/verification/types";

export const ukVerificationOverlay: OverlayFile = ${JSON.stringify(file, null, 2)};
`;
}
